### Get all tunes
GET http://localhost:3000/tunes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NzQ0NDU5MSwiZXhwIjoxNjk3NTMwOTkxfQ.5HiS36CgrOHhR3MHEikOirzWVmMVlkgKCqrV0qPvr7A


### create tune
POST http://localhost:3000/tunes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5NzQ0NDU5MSwiZXhwIjoxNjk3NTMwOTkxfQ.5HiS36CgrOHhR3MHEikOirzWVmMVlkgKCqrV0qPvr7A

{
    "type": "CLASSICAL",
    "artistAlbumId": "1",
    "name": "Soang12",
    "description": "song1",
    "artist": "artist1",
    "rate": "5",
    "source": "http://sjjdfjkala.com",
    "publishedIn": "2020-10-05",
    "language": "ENGLISH",
    "type": "Music",
    "musicType": "PIANO"
}
### Get all tunes
GET http://localhost:3000/tunes/