### Get all
GET http://localhost:3000/music

### create one
POST http://localhost:3000/music
Content-Type: application/json

{
    "type": "KEYBOARD",
    "musicianAlbumId": "1",
    "name": "Song1a1",
    "description": "song1",
    "artist": "artist1",
    "rate": "5",
    "source": "http://skjdfkla.com",
    "publishedIn": "2020-10-05",
    "language": "ENGLISH"
}