### Get all users
GET http://localhost:3000/auth

### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "ahmedelgarhy1",
    "email": "ahmed@gmail.com",
    "password": "password",
    "firstName": "ahmed",
    "lastName": "elgarhy",
    "age": 15,
    "phone": "01205875836",
    "gender": "Male",
    "country": "Egypt",
    "city": "Zagazig",
    "address": "Herit razna"
}

### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    //"username": "ahmedelgarhy1",
    "email": "ahmed@gmail.com",
    "password": "password1"
}

