### Get my favorite
GET http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdlbWF0ZXIuZ0BnbWFpbC5jb20iLCJpYXQiOjE2OTc0NDMyNDEsImV4cCI6MTY5NzUyOTY0MX0.6yDGzQY45j4KWcQhm7OsAU-OQilg8TLtNgouNCnKpFs

### add item
POST http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdlbWF0ZXIuZ0BnbWFpbC5jb20iLCJpYXQiOjE2OTc0NDMyNDEsImV4cCI6MTY5NzUyOTY0MX0.6yDGzQY45j4KWcQhm7OsAU-OQilg8TLtNgouNCnKpFs
Content-Type: application/json

{
    "tuneId": 2
}

### remove item
Delete http://localhost:3000/favorites/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdlbWF0ZXIuZ0BnbWFpbC5jb20iLCJpYXQiOjE2OTc0NDMyNDEsImV4cCI6MTY5NzUyOTY0MX0.6yDGzQY45j4KWcQhm7OsAU-OQilg8TLtNgouNCnKpFs
