### Get all
GET http://localhost:3000/musician-albums

### create one
POST http://localhost:3000/musician-albums
Content-Type: application/json

{
    "type": "KEYBOARD",
    "musicianId": "1",
    "name": "Song1",
    "description": "song1",
    "artist": "artist1",
    "rate": "5",
    "source": "http://skjdfkla.com",
    "publishedIn": "2020-10-05",
    "language": "ENGLISH"
}