### Get all
GET http://localhost:3000/songs

### create one
POST http://localhost:3000/songs
Content-Type: application/json

{
    "type": "CLASSICAL",
    "singerAlbumId": "1",
    "name": "Soang1",
    "description": "song1",
    "artist": "artist1",
    "rate": "5",
    "source": "http://skjdfkla.com",
    "publishedIn": "2020-10-05",
    "language": "ENGLISH"
}