### Get all
GET http://localhost:3000/artists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NzM3ODQ5NywiZXhwIjoxNjk3NDY0ODk3fQ.TqQLtPKIzks-jBa-Zafs-41njyIQ69CgFU4IXHFHae4


### Get all singers
GET http://localhost:3000/artists?type=Singer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NzM3ODQ5NywiZXhwIjoxNjk3NDY0ODk3fQ.TqQLtPKIzks-jBa-Zafs-41njyIQ69CgFU4IXHFHae4

### Get all musicians
GET http://localhost:3000/artists?type=Musician
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NzM3ODQ5NywiZXhwIjoxNjk3NDY0ODk3fQ.TqQLtPKIzks-jBa-Zafs-41njyIQ69CgFU4IXHFHae4

### create one
POST http://localhost:3000/artists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY5NzM3ODQ5NywiZXhwIjoxNjk3NDY0ODk3fQ.TqQLtPKIzks-jBa-Zafs-41njyIQ69CgFU4IXHFHae4

{
    "name": "test3",
    "info": "info",
    "nationality": "nationality1",
    "type": "Musician",
    //"type": "Singer",
    "artistGroupType": "Single",
    "gender": "Male"
}