### Get all
GET http://localhost:3000/singers

### create one
POST http://localhost:3000/singers
Content-Type: application/json

{
    "name": "Musician1",
    "info": "info",
    "nationality": "nationality1",
    "type": "Single",
    "gender": "Male"
}